/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.support.standup.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.support.standup.model.StandUpEntry;
import com.liferay.support.standup.service.GlobalInformationLocalService;
import com.liferay.support.standup.service.GlobalInformationService;
import com.liferay.support.standup.service.StandUpEntryLocalService;
import com.liferay.support.standup.service.StandUpEntryService;
import com.liferay.support.standup.service.persistence.GlobalInformationPersistence;
import com.liferay.support.standup.service.persistence.StandUpEntryPersistence;

import javax.sql.DataSource;

/**
 * The base implementation of the stand up entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.support.standup.service.impl.StandUpEntryServiceImpl}.
 * </p>
 *
 * @author Daniel Javorszky
 * @see com.liferay.support.standup.service.impl.StandUpEntryServiceImpl
 * @see com.liferay.support.standup.service.StandUpEntryServiceUtil
 * @generated
 */
public abstract class StandUpEntryServiceBaseImpl extends BaseServiceImpl
	implements StandUpEntryService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.support.standup.service.StandUpEntryServiceUtil} to access the stand up entry remote service.
	 */

	/**
	 * Returns the global information local service.
	 *
	 * @return the global information local service
	 */
	public GlobalInformationLocalService getGlobalInformationLocalService() {
		return globalInformationLocalService;
	}

	/**
	 * Sets the global information local service.
	 *
	 * @param globalInformationLocalService the global information local service
	 */
	public void setGlobalInformationLocalService(
		GlobalInformationLocalService globalInformationLocalService) {
		this.globalInformationLocalService = globalInformationLocalService;
	}

	/**
	 * Returns the global information remote service.
	 *
	 * @return the global information remote service
	 */
	public GlobalInformationService getGlobalInformationService() {
		return globalInformationService;
	}

	/**
	 * Sets the global information remote service.
	 *
	 * @param globalInformationService the global information remote service
	 */
	public void setGlobalInformationService(
		GlobalInformationService globalInformationService) {
		this.globalInformationService = globalInformationService;
	}

	/**
	 * Returns the global information persistence.
	 *
	 * @return the global information persistence
	 */
	public GlobalInformationPersistence getGlobalInformationPersistence() {
		return globalInformationPersistence;
	}

	/**
	 * Sets the global information persistence.
	 *
	 * @param globalInformationPersistence the global information persistence
	 */
	public void setGlobalInformationPersistence(
		GlobalInformationPersistence globalInformationPersistence) {
		this.globalInformationPersistence = globalInformationPersistence;
	}

	/**
	 * Returns the stand up entry local service.
	 *
	 * @return the stand up entry local service
	 */
	public StandUpEntryLocalService getStandUpEntryLocalService() {
		return standUpEntryLocalService;
	}

	/**
	 * Sets the stand up entry local service.
	 *
	 * @param standUpEntryLocalService the stand up entry local service
	 */
	public void setStandUpEntryLocalService(
		StandUpEntryLocalService standUpEntryLocalService) {
		this.standUpEntryLocalService = standUpEntryLocalService;
	}

	/**
	 * Returns the stand up entry remote service.
	 *
	 * @return the stand up entry remote service
	 */
	public StandUpEntryService getStandUpEntryService() {
		return standUpEntryService;
	}

	/**
	 * Sets the stand up entry remote service.
	 *
	 * @param standUpEntryService the stand up entry remote service
	 */
	public void setStandUpEntryService(StandUpEntryService standUpEntryService) {
		this.standUpEntryService = standUpEntryService;
	}

	/**
	 * Returns the stand up entry persistence.
	 *
	 * @return the stand up entry persistence
	 */
	public StandUpEntryPersistence getStandUpEntryPersistence() {
		return standUpEntryPersistence;
	}

	/**
	 * Sets the stand up entry persistence.
	 *
	 * @param standUpEntryPersistence the stand up entry persistence
	 */
	public void setStandUpEntryPersistence(
		StandUpEntryPersistence standUpEntryPersistence) {
		this.standUpEntryPersistence = standUpEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return StandUpEntry.class;
	}

	protected String getModelClassName() {
		return StandUpEntry.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = standUpEntryPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = GlobalInformationLocalService.class)
	protected GlobalInformationLocalService globalInformationLocalService;
	@BeanReference(type = GlobalInformationService.class)
	protected GlobalInformationService globalInformationService;
	@BeanReference(type = GlobalInformationPersistence.class)
	protected GlobalInformationPersistence globalInformationPersistence;
	@BeanReference(type = StandUpEntryLocalService.class)
	protected StandUpEntryLocalService standUpEntryLocalService;
	@BeanReference(type = StandUpEntryService.class)
	protected StandUpEntryService standUpEntryService;
	@BeanReference(type = StandUpEntryPersistence.class)
	protected StandUpEntryPersistence standUpEntryPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private StandUpEntryServiceClpInvoker _clpInvoker = new StandUpEntryServiceClpInvoker();
}